Exception: df: Column 'z' doesn't exist
